namespace Qwilight
{
    public enum PaintPipelineID
    {
        Media,
        AudioVisualizer,
        MainWall,
        Main,
        AutoInput,
        HitPoints = 6,
        Note,
        Input,
        Band,
        JudgmentMeter,
        Stand,
        Point,
        BPM,
        Multiplier,
        JudgmentPaint,
        Net = 26,
        Unpause,
        Status,
        Hms,
        JudgmentPoints,
        JudgmentMain,
        MainAreaFaint,
        AudioMultiplier,
        HitPointsVisualizer,
        HighestJudgment,
        HigherJudgment,
        HighJudgment,
        LowJudgment,
        LowerJudgment,
        LowestJudgment,
        HighestBand,
        Limiter,
        JudgmentVisualizer,
        InputVisualizer,
        HitNotePaint,
        Hunter,
        Title,
        Artist,
        MediaInput,
        VeilDrawing,
        Genre,
        LevelText,
        AutoMain,
        EarlyValue,
        LateValue,
        JudgmentVSVisualizer,
        MainJudgmentMeter,
        StatusSlider,
        WantLevel,
        Level,
        JudgmentInputVisualizer,
        PaintProperty0 = 100,
        PaintProperty255 = 355
    }
}
