namespace Qwilight
{
    public sealed partial class LanguageSystem
    {
        public string _4DModeContents { get; set; }
        public string AbilityFittedText { get; set; }
        public string AegisPostedItemText { get; set; }
        public string AllowEssentialInputs { get; set; }
        public string AllowTotalLevyingText { get; set; }
        public string AllowTwilightCommentAssist { get; set; }
        public string AlreadyAvatarID { get; set; }
        public string AlreadyLatestDate { get; set; }
        public string AlreadyLoadingBundle { get; set; }
        public string AlwaysNotP2PositionContents { get; set; }
        public string AlwaysNotP2PositionText { get; set; }
        public string AlwaysP2PositionContents { get; set; }
        public string AlwaysP2PositionText { get; set; }
        public string AlwaysText { get; set; }
        public string AlwaysViewContents { get; set; }
        public string Assist0 { get; set; }
        public string Assist1 { get; set; }
        public string Assist2 { get; set; }
        public string Assist3 { get; set; }
        public string Assist4 { get; set; }
        public string Assist5 { get; set; }
        public string Assist6 { get; set; }
        public string Assist7 { get; set; }
        public string Assist8 { get; set; }
        public string Assister { get; set; }
        public string AssistText { get; set; }
        public string AudioAssister { get; set; }
        public string AudioComponentConfigure { get; set; }
        public string AudioConfigureText { get; set; }
        public string AudioDataContents { get; set; }
        public string AudioDateHTMLText { get; set; }
        public string AudioDateText { get; set; }
        public string AudioHandlerItemCountText { get; set; }
        public string AudioInputConfigure { get; set; }
        public string AudioInputValueContents { get; set; }
        public string AudioItemCountText { get; set; }
        public string AudioModeContents { get; set; }
        public string AudioMultiplierAtoneText { get; set; }
        public string AudioMultiplierContents { get; set; }
        public string AudioMultiplierWarning { get; set; }
        public string AudioUnitUsageText { get; set; }
        public string AudioValueContents { get; set; }
        public string AudioVarietyASIOAssist { get; set; }
        public string AudioVarietyText { get; set; }
        public string AudioVarietyWASAPIAssist { get; set; }
        public string AudioVisualizerConfigure { get; set; }
        public string AudioVisualizerCountText { get; set; }
        public string AudioVisualizerFaintContents { get; set; }
        public string AudioVisualizerInputColor { get; set; }
        public string AudioVisualizerMainColor { get; set; }
        public string AudioVisualizerMode0Contents { get; set; }
        public string AudioVisualizerMode1Contents { get; set; }
        public string AudioVisualizerMode2Contents { get; set; }
        public string AudioVisualizerModeText { get; set; }
        public string AudioWaitContents { get; set; }
        public string AuraContents { get; set; }
        public string AuraText { get; set; }
        public string AutoableInputNoteCountViewColor { get; set; }
        public string AutoableLimiterVariety { get; set; }
        public string AutoableModeContents { get; set; }
        public string AutoComputeContents { get; set; }
        public string AutoComputeText { get; set; }
        public string AutoComputingSituationContents { get; set; }
        public string AutoEdgeText { get; set; }
        public string AutoEnterContents { get; set; }
        public string AutoEnterDefaultSiteContents { get; set; }
        public string AutoEnterNotifySiteContents { get; set; }
        public string AutoEnterPlatformSiteContents { get; set; }
        public string AutoEnterSignedInContents { get; set; }
        public string AutoHighlightContents { get; set; }
        public string AutoHighlightText { get; set; }
        public string AutoLevyingContents { get; set; }
        public string AutoLevyingText { get; set; }
        public string AutoLongNoteMode { get; set; }
        public string AutoModeAssist { get; set; }
        public string AutoModeContents { get; set; }
        public string AutoNetLevyingText { get; set; }
        public string AutoSaltAssist { get; set; }
        public string AutoSignIn { get; set; }
        public string AutoSiteHandText { get; set; }
        public string AutoText { get; set; }
        public string AvatarCipher { get; set; }
        public string AvatarCipherTest { get; set; }
        public string AvatarCountContents { get; set; }
        public string AvatarDrawingText { get; set; }
        public string AvatarEdgeText { get; set; }
        public string AvatarHandledAssistClearText { get; set; }
        public string AvatarHandledBand1Text { get; set; }
        public string AvatarHandledClearText { get; set; }
        public string AvatarHandledHigherClearText { get; set; }
        public string AvatarHandledHighestClearText { get; set; }
        public string AvatarHandledNotText { get; set; }
        public string AvatarID { get; set; }
        public string AvatarName { get; set; }
        public string AvatarText { get; set; }
        public string AvatarTitleText { get; set; }
        public string AvatarViewAbilityContents { get; set; }
        public string AvatarViewDateContents { get; set; }
        public string AvatarViewDateText { get; set; }
        public string AvatarViewFavoritesContents { get; set; }
        public string AvatarViewHandledText { get; set; }
        public string AvatarViewHighestCountText { get; set; }
        public string AvatarViewIntro { get; set; }
        public string AvatarViewLastsContents { get; set; }
        public string AvatarViewLevelVSText { get; set; }
        public string AvatarViewQuitContents { get; set; }
        public string AvatarViewText { get; set; }
        public string AvatarViewTotalCountText { get; set; }
        public string AvatarViewTotalLengthText { get; set; }
        public string AvatarViewWwwLevelText { get; set; }
        public string AveragerContents { get; set; }
        public string AveragerText { get; set; }
        public string BanalAudioContents { get; set; }
        public string BanalAudioText { get; set; }
        public string BanalFailedMediaContents { get; set; }
        public string BanalFailedMediaText { get; set; }
        public string BanalMediaContents { get; set; }
        public string BanalMediaText { get; set; }
        public string Band { get; set; }
        public string BandContents { get; set; }
        public string BandLegend { get; set; }
        public string BandPositionContents { get; set; }
        public string BandValidHunterModeText { get; set; }
        public string BannedNoteFileContents { get; set; }
        public string BeforeEventNoteContents { get; set; }
        public string BPMModeAssist { get; set; }
        public string BPMVarietyAudioMultiplierText { get; set; }
        public string BPMVarietyContents { get; set; }
        public string BPMVarietyMultiplierText { get; set; }
        public string BundleAvatarContents { get; set; }
        public string BundleCallableContents { get; set; }
        public string BundleEntryContents { get; set; }
        public string BundleText { get; set; }
        public string BundleUbuntuContents { get; set; }
        public string BundleVoidContents { get; set; }
        public string BWContents { get; set; }
        public string BWText { get; set; }
        public string CallingIOContents { get; set; }
        public string CallIO { get; set; }
        public string CallSiteAssist { get; set; }
        public string CanBeTwilightCommentContents { get; set; }
        public string CannotBeTwilightCommentContents { get; set; }
        public string CannotIOContents { get; set; }
        public string CenterLimiterVariety { get; set; }
        public string ClearedTabText { get; set; }
        public string ColorText { get; set; }
        public string CommentAssist { get; set; }
        public string CommentComputingSituationContents { get; set; }
        public string CommentSiteName { get; set; }
        public string CommentText { get; set; }
        public string CompileFaultText { get; set; }
        public string CompilingBinText { get; set; }
        public string ComponentConfigure { get; set; }
        public string ComputingConfigureText { get; set; }
        public string ComputingGUIConfigure { get; set; }
        public string ComputingModeComponentConfigure { get; set; }
        public string ComputingUIConfigure { get; set; }
        public string ConfigureAssist { get; set; }
        public string ConfigureBaseUIContents { get; set; }
        public string ConfigureEtcUIContents { get; set; }
        public string ConfigureFontFamilyContents { get; set; }
        public string ConfigureInputFavorLabelledMillisContents { get; set; }
        public string ConfigureLevelContents { get; set; }
        public string ConfigureSetNotePutContents { get; set; }
        public string ConfigureSetNotePutMillisContents { get; set; }
        public string ConfigureText { get; set; }
        public string ConfigureUIContents { get; set; }
        public string ControllerConfigure { get; set; }
        public string ControllerCountContents { get; set; }
        public string ControllerViewerContents { get; set; }
        public string CopyPutCopyNotesText { get; set; }
        public string CountContents { get; set; }
        public string CounterWaveModeContents { get; set; }
        public string D2DSystemFault { get; set; }
        public string DataCount3Contents { get; set; }
        public string DataCount3Text { get; set; }
        public string DateAssistText { get; set; }
        public string DateText0 { get; set; }
        public string DateText1 { get; set; }
        public string DateText2 { get; set; }
        public string DateText3 { get; set; }
        public string DBConfigure { get; set; }
        public string DefaultAudioFilePathText { get; set; }
        public string DefaultAudioVarietyContents { get; set; }
        public string DefaultBPMModeContents { get; set; }
        public string DefaultBundleCompetenceContents { get; set; }
        public string DefaultComment { get; set; }
        public string DefaultComputeInNetSiteFault { get; set; }
        public string DefaultComputingSituationContents { get; set; }
        public string DefaultConfigureText { get; set; }
        public string DefaultControllerDefaultInputContents { get; set; }
        public string DefaultControllerDefaultInputText { get; set; }
        public string DefaultControllerDInputContents { get; set; }
        public string DefaultControllerDInputText { get; set; }
        public string DefaultControllerViewerContents { get; set; }
        public string DefaultDrawingContents { get; set; }
        public string DefaultFaintNoteModeContents { get; set; }
        public string DefaultGPUMode { get; set; }
        public string DefaultHitPointsModeContents { get; set; }
        public string DefaultInputAudioVariety { get; set; }
        public string DefaultInputAudioVarietyAssist { get; set; }
        public string DefaultJudgmentModeContents { get; set; }
        public string DefaultLongNoteMode { get; set; }
        public string DefaultLowestJudgmentConditionModeContents { get; set; }
        public string DefaultMobilityMode { get; set; }
        public string DefaultModeContents { get; set; }
        public string DefaultNoteAssister { get; set; }
        public string DefaultNoteModifyContents { get; set; }
        public string DefaultPutCopyNotesText { get; set; }
        public string DefaultSaltModeContents { get; set; }
        public string DefaultSetNoteModeContents { get; set; }
        public string DefaultSiteName { get; set; }
        public string DefaultWaveModeContents { get; set; }
        public string DetailedConfigure { get; set; }
        public string DetailedConfigureText { get; set; }
        public string DInputContents { get; set; }
        public string DInputControllerVarietyText { get; set; }
        public string DInputIIDXSensitivityText { get; set; }
        public string DInputText { get; set; }
        public string DInputXyzSensitivityText { get; set; }
        public string DrawingComponentConfigure { get; set; }
        public string DrawingItemCountText { get; set; }
        public string Easy4DModeContents { get; set; }
        public string EasyZipModeContents { get; set; }
        public string EditedNoteFileFault { get; set; }
        public string EditorConfigureFault { get; set; }
        public string EditorContents { get; set; }
        public string EditorSoftwareFault { get; set; }
        public string EnterAutoComputeConfigure { get; set; }
        public string EnterAutoComputeMediaInputConfigure { get; set; }
        public string EnterAutoComputeUIConfigure { get; set; }
        public string EnterSiteCipherContents { get; set; }
        public string EnterSiteInputContents { get; set; }
        public string EqualizerContents { get; set; }
        public string EqualizerText { get; set; }
        public string EventNote { get; set; }
        public string EventNoteBundleText { get; set; }
        public string EventNoteEntryContents { get; set; }
        public string EventNoteNameAssist { get; set; }
        public string ExileAvatar { get; set; }
        public string F5Notify0 { get; set; }
        public string F5Notify1 { get; set; }
        public string FadingNoteModeContents { get; set; }
        public string FailedDrawingMillisText { get; set; }
        public string FailedHitPointsModeContents { get; set; }
        public string FailedValidation { get; set; }
        public string FailedVibrationModeText { get; set; }
        public string FaintNoteAssist { get; set; }
        public string FaintNoteModeContents { get; set; }
        public string FastInputMillisContents { get; set; }
        public string FaultCommentContents { get; set; }
        public string FaultStillDrawing { get; set; }
        public string FavorAudioMultiplierText { get; set; }
        public string FavorDefaultAudioVarietyText { get; set; }
        public string FavorHitPoints0Unit { get; set; }
        public string FavorHitPoints1Unit { get; set; }
        public string FavorHitPointsModeContents { get; set; }
        public string FavorHitPointsNameAssist { get; set; }
        public string FavoriteEntryText { get; set; }
        public string FavorJudgmentModeContents { get; set; }
        public string FavorJudgmentNameAssist { get; set; }
        public string FavorMediaInputContents { get; set; }
        public string FavorModeComponentText { get; set; }
        public string FavorMultiplierText { get; set; }
        public string FavorNoteFileText { get; set; }
        public string Fax { get; set; }
        public string FitAssist { get; set; }
        public string FitDefaultEntry { get; set; }
        public string FlangeContents { get; set; }
        public string FlangeText { get; set; }
        public string FlowValuesContents { get; set; }
        public string FlowValuesText { get; set; }
        public string FontFamilyAssist { get; set; }
        public string FontFamilyText { get; set; }
        public string FrontEntryText { get; set; }
        public string GASWarning { get; set; }
        public string GetMediaInputContents { get; set; }
        public string GetMediaInputText { get; set; }
        public string GetMIDIText { get; set; }
        public string GetQwilightFault { get; set; }
        public string GetQwilightText { get; set; }
        public string GetWaveInValuesText { get; set; }
        public string GetWaveValuesText { get; set; }
        public string GetWwwLevel { get; set; }
        public string GPUModeModified { get; set; }
        public string GPUModeText { get; set; }
        public string GroupEntry0Assist { get; set; }
        public string GroupEntry1Assist { get; set; }
        public string GUIConfigureText { get; set; }
        public string HalfInputSaltModeContents { get; set; }
        public string HandledAssistClearText { get; set; }
        public string HandledBand1Text { get; set; }
        public string HandledClearText { get; set; }
        public string HandledContents { get; set; }
        public string HandledFText { get; set; }
        public string HandledHigherClearText { get; set; }
        public string HandledHighestClearText { get; set; }
        public string HandledNotText { get; set; }
        public string HandleFailedAudioCountText { get; set; }
        public string HandleFailedAudioText { get; set; }
        public string HandleInputAudioContents { get; set; }
        public string HandleInputAudioText { get; set; }
        public string HandleMeterContents { get; set; }
        public string HandleMeterText { get; set; }
        public string HandleUndoContents { get; set; }
        public string HandlingAudioCountText { get; set; }
        public string HandlingCountContents { get; set; }
        public string HasNotEventNoteNoteFile { get; set; }
        public string HasNotIONoteFile { get; set; }
        public string HasNotNetNoteFile { get; set; }
        public string HellBPMContents { get; set; }
        public string HellBPMText { get; set; }
        public string HigherAudioMultiplierContents { get; set; }
        public string HigherEntryContents { get; set; }
        public string HigherHitPointsModeContents { get; set; }
        public string HigherJudgmentModeContents { get; set; }
        public string HigherLongNoteMode { get; set; }
        public string HigherMultiplierContents { get; set; }
        public string HigherNoteFileContents { get; set; }
        public string HighestHitPointsModeContents { get; set; }
        public string HighestJudgmentModeContents { get; set; }
        public string HighestLongNoteModify { get; set; }
        public string HighestWantBPMContents { get; set; }
        public string HighestWantInputCountContents { get; set; }
        public string HighestWantLevelTextValue { get; set; }
        public string HitNotePaintAreaContents { get; set; }
        public string HitPoints { get; set; }
        public string HitPointsLegend { get; set; }
        public string HitPointsModeAssist { get; set; }
        public string HOFAbilityText { get; set; }
        public string HOFAtText { get; set; }
        public string HOFBand { get; set; }
        public string HOFHighest { get; set; }
        public string HOFLevelText { get; set; }
        public string HOFStand { get; set; }
        public string HOFText { get; set; }
        public string HOFTotal { get; set; }
        public string HOFTotalText { get; set; }
        public string HunterVariety1stText { get; set; }
        public string HunterVarietyContents { get; set; }
        public string HunterVarietyFavorText { get; set; }
        public string HunterVarietyHigherText { get; set; }
        public string HunterVarietyLowerText { get; set; }
        public string HunterVarietyMeText { get; set; }
        public string HwModeContents { get; set; }
        public string IIDXInputAudioVariety { get; set; }
        public string IIDXInputAudioVarietyAssist { get; set; }
        public string InitColorContents { get; set; }
        public string InitColorNotify { get; set; }
        public string InitColorOK { get; set; }
        public string InitColorText { get; set; }
        public string InitCommentContents { get; set; }
        public string InitCommentNotify { get; set; }
        public string InitCommentOK { get; set; }
        public string InitCommentText { get; set; }
        public string InitCompiledContents { get; set; }
        public string InitCompiledNotify { get; set; }
        public string InitCompiledOK { get; set; }
        public string InitCompiledText { get; set; }
        public string InitEqualizerContents { get; set; }
        public string InitFavoriteEntryContents { get; set; }
        public string InitFavoriteEntryNotify { get; set; }
        public string InitFavoriteEntryOK { get; set; }
        public string InitFavoriteEntryText { get; set; }
        public string InitMediaContents { get; set; }
        public string InitMediaNotify { get; set; }
        public string InitMediaOK { get; set; }
        public string InitMediaText { get; set; }
        public string InitModeComponent { get; set; }
        public string InitTotalContents { get; set; }
        public string InitTotalNotify { get; set; }
        public string InitTotalOK { get; set; }
        public string InitTotalText { get; set; }
        public string InitWaitContents { get; set; }
        public string InitWaitNotify { get; set; }
        public string InitWaitOK { get; set; }
        public string InitWaitText { get; set; }
        public string InputAudioVarietyText { get; set; }
        public string InputAudioVolume { get; set; }
        public string InputConfigure { get; set; }
        public string InputConfigureText { get; set; }
        public string InputDefaultMode { get; set; }
        public string InputFavorLabelledAssist { get; set; }
        public string InputFavorMode10 { get; set; }
        public string InputFavorMode102 { get; set; }
        public string InputFavorMode142 { get; set; }
        public string InputFavorMode242 { get; set; }
        public string InputFavorMode4 { get; set; }
        public string InputFavorMode484 { get; set; }
        public string InputFavorMode5 { get; set; }
        public string InputFavorMode51 { get; set; }
        public string InputFavorMode6 { get; set; }
        public string InputFavorMode7 { get; set; }
        public string InputFavorMode71 { get; set; }
        public string InputFavorMode8 { get; set; }
        public string InputFavorMode9 { get; set; }
        public string InputFavorModeAssist { get; set; }
        public string InputFavorModeFill10 { get; set; }
        public string InputFavorModeFill102 { get; set; }
        public string InputFavorModeFill142 { get; set; }
        public string InputFavorModeFill242 { get; set; }
        public string InputFavorModeFill4 { get; set; }
        public string InputFavorModeFill484 { get; set; }
        public string InputFavorModeFill5 { get; set; }
        public string InputFavorModeFill51 { get; set; }
        public string InputFavorModeFill6 { get; set; }
        public string InputFavorModeFill7 { get; set; }
        public string InputFavorModeFill71 { get; set; }
        public string InputFavorModeFill8 { get; set; }
        public string InputFavorModeFill9 { get; set; }
        public string InputMapText { get; set; }
        public string InputNoteCountViewColor { get; set; }
        public string InputSaltModeContents { get; set; }
        public string InputVibrationModeText { get; set; }
        public string InputWantAssist { get; set; }
        public string InputWindowAssist0 { get; set; }
        public string InputWindowAssist1 { get; set; }
        public string InputWindowAssist2 { get; set; }
        public string InputWindowAssist3 { get; set; }
        public string InsetNotePutContents { get; set; }
        public string IOAvatarContents { get; set; }
        public string IOCallableContents { get; set; }
        public string IOCompetenceContents { get; set; }
        public string IOComputingSituationContents { get; set; }
        public string IOHigherContents { get; set; }
        public string IOLowerContents { get; set; }
        public string IOUbuntuContents { get; set; }
        public string IOVoidContents { get; set; }
        public string IsAudioInputContents { get; set; }
        public string IsFailModeContents { get; set; }
        public string IsFailModeText { get; set; }
        public string IsGetNotifyContents { get; set; }
        public string IsXwindowContents { get; set; }
        public string JudgmentMainPosition1Contents { get; set; }
        public string JudgmentMeterMillisText { get; set; }
        public string JudgmentModeAssist { get; set; }
        public string JudgmentPaintPositionContents { get; set; }
        public string JudgmentStage { get; set; }
        public string JudgmentVisualizerMillisText { get; set; }
        public string JudgmentVisualizerPositionContents { get; set; }
        public string K70Contents { get; set; }
        public string K70Text { get; set; }
        public string LazyGCText { get; set; }
        public string Level0Contents { get; set; }
        public string Level1Contents { get; set; }
        public string Level2Contents { get; set; }
        public string Level3Contents { get; set; }
        public string Level4Contents { get; set; }
        public string Level5Contents { get; set; }
        public string LevelInputContents { get; set; }
        public string LevelItem { get; set; }
        public string LevelSystemText { get; set; }
        public string LevelVSStandContents { get; set; }
        public string LevyNoteFileContents { get; set; }
        public string LevyWwwLevel { get; set; }
        public string Library { get; set; }
        public string Limiter57Variety { get; set; }
        public string LimiterColor { get; set; }
        public string LimiterVarietyContents { get; set; }
        public string LoadBanalAudio { get; set; }
        public string LoadBanalFailedMedia { get; set; }
        public string LoadBanalMedia { get; set; }
        public string LoadDefaultAudio { get; set; }
        public string LoadedModeComponent { get; set; }
        public string LoadedMultiplier { get; set; }
        public string LoadingBinText { get; set; }
        public string LoadLevelFault { get; set; }
        public string LongNoteModeAssist { get; set; }
        public string LongNoteModifyAssist { get; set; }
        public string LongNoteModifyContents { get; set; }
        public string LongNoteModifyFaultText { get; set; }
        public string LoopUnitText { get; set; }
        public string LoopWaveInContents { get; set; }
        public string LoopWaveInText { get; set; }
        public string LostPointAudioContents { get; set; }
        public string LostPointAudioText { get; set; }
        public string LowerAudioMultiplierContents { get; set; }
        public string LowerEntryContents { get; set; }
        public string LowerHitPointsModeContents { get; set; }
        public string LowerJudgmentModeContents { get; set; }
        public string LowerMultiplierContents { get; set; }
        public string LowerNoteFileContents { get; set; }
        public string LowestHitPointsModeContents { get; set; }
        public string LowestJudgmentConditionModeAssist { get; set; }
        public string LowestJudgmentModeContents { get; set; }
        public string LowestLongNoteModify { get; set; }
        public string LowestWantBPMContents { get; set; }
        public string LowestWantInputCountContents { get; set; }
        public string LowestWantLevelTextValue { get; set; }
        public string LowHitPointsFaintUIContents { get; set; }
        public string LowHitPointsFaintUIText { get; set; }
        public string LSCompileFault { get; set; }
        public string LSContents { get; set; }
        public string LSText { get; set; }
        public string MainAreaFaintContents { get; set; }
        public string MainControllerPowerText { get; set; }
        public string MainFaintContents { get; set; }
        public string MainPositionContents { get; set; }
        public string MainSetContents { get; set; }
        public string MediaComponentConfigure { get; set; }
        public string MediaConfigure { get; set; }
        public string MediaContents { get; set; }
        public string MediaFaintContents { get; set; }
        public string MediaFillContents { get; set; }
        public string MediaFillText { get; set; }
        public string MediaHandlerItemCountText { get; set; }
        public string MediaInputConfigure { get; set; }
        public string MediaInputFaintContents { get; set; }
        public string MediaInputQualityContents { get; set; }
        public string MediaItemCountText { get; set; }
        public string MediaModifierContents { get; set; }
        public string MediaText { get; set; }
        public string MediaWaitContents { get; set; }
        public string MeterNoteColor { get; set; }
        public string MeterSaltModeContents { get; set; }
        public string MIDIConfigure { get; set; }
        public string MIDICountContents { get; set; }
        public string MIDIPBCSensitivityText { get; set; }
        public string MIDIViewerContents { get; set; }
        public string MITMFaultText { get; set; }
        public string ModifyAutoModeContents { get; set; }
        public string ModifyDefaultEntryAssist0 { get; set; }
        public string ModifyDefaultEntryText { get; set; }
        public string ModifyEditorContents { get; set; }
        public string ModifyEventNoteName { get; set; }
        public string ModifyEventNoteNameContents { get; set; }
        public string ModifyFavoriteEntry { get; set; }
        public string ModifyFavoriteEntryName { get; set; }
        public string ModifyFavoriteEntryNameContents { get; set; }
        public string ModifyFrontEntry { get; set; }
        public string ModifyModeComponentText { get; set; }
        public string ModifyPositionAssist { get; set; }
        public string MultiplierContents { get; set; }
        public string NegativePostedItemText { get; set; }
        public string NegativeStopFault { get; set; }
        public string NetCommentFollowContents { get; set; }
        public string NetCommentFollowText { get; set; }
        public string NetCommentNotFollowContents { get; set; }
        public string NetCommentNotFollowText { get; set; }
        public string NetComputingSituationContents { get; set; }
        public string NetItemCountText { get; set; }
        public string NetItemFaintContents { get; set; }
        public string NetSiteCommentsText { get; set; }
        public string NetTabText { get; set; }
        public string NetUIContents { get; set; }
        public string NewDefaultAudioFilePath { get; set; }
        public string NewDefaultEntry { get; set; }
        public string NewEventNote { get; set; }
        public string NewFavoriteEntry { get; set; }
        public string NewFavoriteEntryContents { get; set; }
        public string NewFrontEntry { get; set; }
        public string NewNetSiteContents { get; set; }
        public string NewNetSiteText { get; set; }
        public string NewSilentSite { get; set; }
        public string NewSiteContents { get; set; }
        public string NewSiteText { get; set; }
        public string NewTitleContents { get; set; }
        public string NewUbuntu { get; set; }
        public string NotAllowPauseText { get; set; }
        public string NotAuraText { get; set; }
        public string NotAutoComputeConfigureFault { get; set; }
        public string NotAutoComputeContents { get; set; }
        public string NotAutoComputeFault { get; set; }
        public string NotAutoComputeText { get; set; }
        public string NotAutoComputeViewContents { get; set; }
        public string NotAvailableEventNoteFileFault { get; set; }
        public string NotAvailableLevelWww { get; set; }
        public string NotAvatarBundleFault { get; set; }
        public string NotAvatarGroup { get; set; }
        public string NotAvatarTitle { get; set; }
        public string NotAvatarUbuntuFault { get; set; }
        public string NotAvatarViewFault { get; set; }
        public string NotAveragerText { get; set; }
        public string NotBanalAudioText { get; set; }
        public string NotBanalFailedMediaText { get; set; }
        public string NotBanalMediaText { get; set; }
        public string NotBPMModeContents { get; set; }
        public string NotBWText { get; set; }
        public string NotDataCount3Text { get; set; }
        public string NotDefaultAudioVarietyText { get; set; }
        public string NoteDrawingCountText { get; set; }
        public string NoteFileBundleText { get; set; }
        public string NoteFileLevelText { get; set; }
        public string NoteFileModeSituationContents { get; set; }
        public string NoteFilesBundleText { get; set; }
        public string NoteFilesLevelText { get; set; }
        public string NoteFormat { get; set; }
        public string NoteFormatIDText65001 { get; set; }
        public string NoteFormatIDText932 { get; set; }
        public string NoteFormatIDText936 { get; set; }
        public string NoteFormatIDText949 { get; set; }
        public string NoteHeightContents { get; set; }
        public string NoteLengthContents { get; set; }
        public string NoteMobilityAssist { get; set; }
        public string NoteModifyModeAssist { get; set; }
        public string NoteSaltCommentWarning { get; set; }
        public string NoteSaltModeAssist { get; set; }
        public string NoteWaitContents { get; set; }
        public string NotFavoritesF10 { get; set; }
        public string NotFlangeText { get; set; }
        public string NotFlowValuesText { get; set; }
        public string NotHandleInputAudioText { get; set; }
        public string NotHandleMeterText { get; set; }
        public string NotHaveLevelTarget { get; set; }
        public string NotHaveNoteFileEntryText { get; set; }
        public string NotHellBPMText { get; set; }
        public string NotifyInSite { get; set; }
        public string NotifySaveBundleAvatarContents { get; set; }
        public string NotifySaveBundleCallableContents { get; set; }
        public string NotifySaveBundleCompetenceContents { get; set; }
        public string NotifySaveBundleUbuntuContents { get; set; }
        public string NotifySaveBundleVoidContents { get; set; }
        public string NotifySiteName { get; set; }
        public string NotifySiteYellInvite { get; set; }
        public string NotifySiteYellTV { get; set; }
        public string NotifyText { get; set; }
        public string NotifyUbuntuCompetenceContents { get; set; }
        public string NotifyUbuntuContents { get; set; }
        public string NotIsFailModeContents { get; set; }
        public string NotIsFailModeText { get; set; }
        public string NotK70Text { get; set; }
        public string NotLoopWaveInContents { get; set; }
        public string NotLoopWaveInText { get; set; }
        public string NotLostPointAudioText { get; set; }
        public string NotLowHitPointsFaintUIText { get; set; }
        public string NotLSText { get; set; }
        public string NotMediaFillContents { get; set; }
        public string NotMediaFillText { get; set; }
        public string NotMediaText { get; set; }
        public string NotNotifyUbuntuContents { get; set; }
        public string NotQwilightFillContents { get; set; }
        public string NotQwilightFillText { get; set; }
        public string NotSFXText { get; set; }
        public string NotSignedInContents { get; set; }
        public string NotSignedInSituationContents { get; set; }
        public string NotSignInNotify { get; set; }
        public string NotSignInText { get; set; }
        public string NotStillDrawing { get; set; }
        public string NotStopLastEqualAudioText { get; set; }
        public string NotSupportedFileContents { get; set; }
        public string NotTubeText { get; set; }
        public string NotUbuntuSituationContents { get; set; }
        public string NotValidNetLevelContents { get; set; }
        public string NotValidNoteFile { get; set; }
        public string NotVESAText { get; set; }
        public string NotVibrationModeText { get; set; }
        public string NotViewContents { get; set; }
        public string NotWantHandledContents { get; set; }
        public string NotWantLevelContents { get; set; }
        public string NotWantLevelItemContents { get; set; }
        public string NotWantModeContents { get; set; }
        public string NotWantNoteVarietyContents { get; set; }
        public string NotWindowedModeContents { get; set; }
        public string NotWindowedModeText { get; set; }
        public string NotXwindowText { get; set; }
        public string NVLLFramerateContents { get; set; }
        public string NVLLModeContents { get; set; }
        public string NVLLModeNotText { get; set; }
        public string NVLLModeOKText { get; set; }
        public string NVLLModeUnlimitedText { get; set; }
        public string OBSText0 { get; set; }
        public string OBSText1 { get; set; }
        public string OpenedCountContents { get; set; }
        public string OpenedEventNotes { get; set; }
        public string OpenedUIFileContents { get; set; }
        public string OpeningUIFileContents { get; set; }
        public string P1SymmetricCopyNotesText { get; set; }
        public string P2SymmetricCopyNotesText { get; set; }
        public string PassContents { get; set; }
        public string PauseAssist { get; set; }
        public string PlatformAutoComputing { get; set; }
        public string PlatformCommentComputing { get; set; }
        public string PlatformDefaultComputing { get; set; }
        public string PlatformNoteFileMode { get; set; }
        public string PlatformQuitMode { get; set; }
        public string PlatformSiteName { get; set; }
        public string PlatformText0 { get; set; }
        public string PlatformText1 { get; set; }
        public string Point { get; set; }
        public string PointLegend { get; set; }
        public string PointLevelContents { get; set; }
        public string PointValidHunterModeText { get; set; }
        public string PositivePostedItemText { get; set; }
        public string PostableItemModeViewCommentFault { get; set; }
        public string PostableItemModeWarning { get; set; }
        public string PostableItemTabText { get; set; }
        public string PostItem0Contents { get; set; }
        public string PostItem1Contents { get; set; }
        public string PostItemContents { get; set; }
        public string Power00 { get; set; }
        public string Power01 { get; set; }
        public string Power02 { get; set; }
        public string Power03 { get; set; }
        public string Power04 { get; set; }
        public string Power10 { get; set; }
        public string Power11 { get; set; }
        public string Power12 { get; set; }
        public string Power13 { get; set; }
        public string PutCopyNotesContents { get; set; }
        public string PutSetNoteModeContents { get; set; }
        public string QuitComputingSituationContents { get; set; }
        public string QuitContents { get; set; }
        public string QuitSiteAssist { get; set; }
        public string QuitText { get; set; }
        public string QwilightBundleText { get; set; }
        public string QwilightFillContents { get; set; }
        public string QwilightFillText { get; set; }
        public string SaltContents { get; set; }
        public string SaltModeContents { get; set; }
        public string SaveAsBundle { get; set; }
        public string SaveAsBundleContents { get; set; }
        public string SaveAsBundleFault { get; set; }
        public string SaveAsNetBundle { get; set; }
        public string SaveBundle { get; set; }
        public string SaveBundleContents { get; set; }
        public string SaveBundleFault { get; set; }
        public string SaveCommentFailed { get; set; }
        public string SavedAsBundleContents { get; set; }
        public string SavedBundleContents { get; set; }
        public string SavedDefaultNoteContents { get; set; }
        public string SavedDefaultUIContents { get; set; }
        public string SaveDefaultNoteContents { get; set; }
        public string SaveDefaultNoteNotify { get; set; }
        public string SaveDefaultNoteText { get; set; }
        public string SaveDefaultUIContents { get; set; }
        public string SaveDefaultUINotify { get; set; }
        public string SaveDefaultUIText { get; set; }
        public string SavedFileContents { get; set; }
        public string SavedLevelContents { get; set; }
        public string SavedQwilightBundleContents { get; set; }
        public string SavedQwilightContents { get; set; }
        public string SavedStillDrawing { get; set; }
        public string SavedUIContents { get; set; }
        public string SaveFileFault { get; set; }
        public string SaveModeComponent { get; set; }
        public string SaveModeComponentContents { get; set; }
        public string SaveNetBundle { get; set; }
        public string SaveUIFault { get; set; }
        public string SavingAsBundleContents { get; set; }
        public string SavingBundleContents { get; set; }
        public string SavingDefaultNotesContents { get; set; }
        public string SavingDefaultUIContents { get; set; }
        public string SavingFileContents { get; set; }
        public string SavingLevelContents { get; set; }
        public string SavingQwilightContents { get; set; }
        public string SavingUIContents { get; set; }
        public string SetAutoNoteWait { get; set; }
        public string SetEntryItem { get; set; }
        public string SetFavoritesF10 { get; set; }
        public string SetNoteFile { get; set; }
        public string SetNoteModeAssist { get; set; }
        public string SetNotePutAssist { get; set; }
        public string SetNotTotalText { get; set; }
        public string SetPostItemInputText { get; set; }
        public string SetSaltText { get; set; }
        public string SetSiteHand { get; set; }
        public string SetSiteName { get; set; }
        public string SetSiteNameContents { get; set; }
        public string SetTotalText { get; set; }
        public string SFXContents { get; set; }
        public string SFXText { get; set; }
        public string SignIn { get; set; }
        public string SignUp { get; set; }
        public string SilentSiteAvatarContents { get; set; }
        public string SilentSiteCallableContents { get; set; }
        public string SilentSiteCompetenceContents { get; set; }
        public string SilentSiteUbuntuContents { get; set; }
        public string SilentSiteVoidContents { get; set; }
        public string SiteCipher { get; set; }
        public string SiteHandLevyingText { get; set; }
        public string SiteInputAssist { get; set; }
        public string SiteLevyingText { get; set; }
        public string SiteText { get; set; }
        public string SiteYellEnter { get; set; }
        public string SiteYellInvite { get; set; }
        public string SiteYellNewNetSite { get; set; }
        public string SiteYellNewSite { get; set; }
        public string SiteYellQuit { get; set; }
        public string SiteYellTaehui { get; set; }
        public string SiteYellTV { get; set; }
        public string SlowLoopingContents { get; set; }
        public string SoftwareAssister { get; set; }
        public string Stand { get; set; }
        public string StandardControllerModeContents { get; set; }
        public string StandardControllerModeText { get; set; }
        public string StandardDefaultControllerModeContents { get; set; }
        public string StandardDefaultControllerModeText { get; set; }
        public string StandardMIDIModeContents { get; set; }
        public string StandardMIDIModeText { get; set; }
        public string StandardWaitUnitContents { get; set; }
        public string StandContents { get; set; }
        public string StandLegend { get; set; }
        public string StandValidHunterModeText { get; set; }
        public string StopLastEqualAudioContents { get; set; }
        public string StopLastEqualAudioText { get; set; }
        public string StopSavingAsBundleContents { get; set; }
        public string StopSavingBundleContents { get; set; }
        public string StopSiteNetText { get; set; }
        public string SuccessfullySignedInContents { get; set; }
        public string SymmetricModeContents { get; set; }
        public string TestHitPointsModeContents { get; set; }
        public string TestHitPointsModeWarning { get; set; }
        public string TotalAudioVolume { get; set; }
        public string TotalFadingNoteModeContents { get; set; }
        public string TotalLimiterVariety { get; set; }
        public string TotalVarietyContents { get; set; }
        public string TubeContents { get; set; }
        public string TubeText { get; set; }
        public string Tutorial0 { get; set; }
        public string Tutorial1 { get; set; }
        public string Tutorial20 { get; set; }
        public string Tutorial200 { get; set; }
        public string Tutorial201 { get; set; }
        public string Tutorial21 { get; set; }
        public string Tutorial22 { get; set; }
        public string Tutorial220 { get; set; }
        public string TutorialAssistText { get; set; }
        public string TutorialID0 { get; set; }
        public string TutorialID1 { get; set; }
        public string TutorialID2 { get; set; }
        public string TutorialID3 { get; set; }
        public string TVAssistConfigure { get; set; }
        public string TwilightCloseContents { get; set; }
        public string TwilightComment { get; set; }
        public string TwilightCommentaryAssist { get; set; }
        public string TwilightCommentIOContents { get; set; }
        public string TwilightCommentWarning { get; set; }
        public string TwilightConfigure { get; set; }
        public string TwilightConfigureAssist { get; set; }
        public string UbuntuAssist { get; set; }
        public string UbuntuNetItemTargetAssist { get; set; }
        public string UbuntuText { get; set; }
        public string UIAssister { get; set; }
        public string UIBinText { get; set; }
        public string UIBundleText { get; set; }
        public string UICommentNote { get; set; }
        public string UIDefaultAudioVarietyText { get; set; }
        public string UIFaultText { get; set; }
        public string UIHitNotePaint { get; set; }
        public string UIHunter { get; set; }
        public string UIJudgmentCount { get; set; }
        public string UIJudgmentInputVisualizer { get; set; }
        public string UIJudgmentMain { get; set; }
        public string UIJudgmentMeter { get; set; }
        public string UIJudgmentPaint { get; set; }
        public string UIJudgmentVisualizer { get; set; }
        public string UILimiter { get; set; }
        public string UIMainDrawingPaint { get; set; }
        public string UIMainJudgmentMeter { get; set; }
        public string UINet { get; set; }
        public string UndoContents { get; set; }
        public string VeilDrawingHeightContents { get; set; }
        public string VESAContents { get; set; }
        public string VESAText { get; set; }
        public string Vibration0 { get; set; }
        public string Vibration1 { get; set; }
        public string Vibration2 { get; set; }
        public string Vibration3 { get; set; }
        public string VibrationModeContents { get; set; }
        public string ViewAvatarView { get; set; }
        public string ViewBundle { get; set; }
        public string ViewFailedDrawingText { get; set; }
        public string ViewLowestJudgmentText { get; set; }
        public string ViewQwilightEntry { get; set; }
        public string ViewUIEntry { get; set; }
        public string VisibleWindowValuesContents { get; set; }
        public string VoidPutSetNoteModeContents { get; set; }
        public string VoteText { get; set; }
        public string WaitContents { get; set; }
        public string WaitingIOContents { get; set; }
        public string WaitingNetContents { get; set; }
        public string WaitingNotifyContents { get; set; }
        public string WaitSiteContents { get; set; }
        public string WaitUnitContents { get; set; }
        public string WantAverageInputCountContents { get; set; }
        public string WantBannedContents { get; set; }
        public string WantBPMContents { get; set; }
        public string WantHighestInputCountContents { get; set; }
        public string WantLevel { get; set; }
        public string WantLevelItemContents { get; set; }
        public string WantLevelTextValueContents { get; set; }
        public string WantNotBannedText { get; set; }
        public string WantText { get; set; }
        public string WantTotalBannedText { get; set; }
        public string WaveContents { get; set; }
        public string WaveFadeVolumeContents { get; set; }
        public string WaveFault { get; set; }
        public string WaveInContents { get; set; }
        public string WaveInFault { get; set; }
        public string WaveModeAssist { get; set; }
        public string WGIContents { get; set; }
        public string WGIText { get; set; }
        public string WindowedModeContents { get; set; }
        public string WindowedModeText { get; set; }
        public string WipeBundleNotify { get; set; }
        public string WipeBundleText { get; set; }
        public string WipeCommentNotify { get; set; }
        public string WipeDefaultEntryNotify { get; set; }
        public string WipedSiteYell { get; set; }
        public string WipeEntryItemNotify { get; set; }
        public string WipeEntryOK { get; set; }
        public string WipeEventNoteNotify { get; set; }
        public string WipeFavoriteEntryNotify { get; set; }
        public string WipeFavoritesF10 { get; set; }
        public string WipeHandled { get; set; }
        public string WipeLevelNotify { get; set; }
        public string WipeNoteFileNotify { get; set; }
        public string WipeNoteFileOK { get; set; }
        public string WipeTotalNotify { get; set; }
        public string WipeUbuntuNotify { get; set; }
        public string WrongLowestJudgmentConditionModeContents { get; set; }
        public string WwwLevelAudioMultiplierContents0 { get; set; }
        public string WwwLevelAudioMultiplierContents1 { get; set; }
        public string WwwLevelBandContents0 { get; set; }
        public string WwwLevelBandContents1 { get; set; }
        public string WwwLevelClause { get; set; }
        public string WwwLevelClearAvatars { get; set; }
        public string WwwLevelClearAwards { get; set; }
        public string WwwLevelClearAwardsEdge { get; set; }
        public string WwwLevelClearAwardsTitle { get; set; }
        public string WwwLevelClearContents { get; set; }
        public string WwwLevelJudgmentContents0 { get; set; }
        public string WwwLevelJudgmentContents1 { get; set; }
        public string WwwLevelPointContents0 { get; set; }
        public string WwwLevelPointContents1 { get; set; }
        public string WwwLevelStandContents0 { get; set; }
        public string WwwLevelStandContents1 { get; set; }
        public string WwwLevelTabText { get; set; }
        public string WwwLevelTest { get; set; }
        public string WwwLevelText { get; set; }
        public string XInputContents { get; set; }
        public string XInputText { get; set; }
        public string XwindowText { get; set; }
        public string YAMLCompileFault { get; set; }
        public string ZipModeContents { get; set; }
    }
}
