// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Comment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Comment.proto</summary>
public static partial class CommentReflection {

  #region Descriptor
  /// <summary>File descriptor for Comment.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommentReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1Db21tZW50LnByb3RvIq4DCgdDb21tZW50EgwKBGRhdGUYASABKAkSFwoP",
          "aGlnaGVzdEp1ZGdtZW50GAIgASgFEhYKDmhpZ2hlckp1ZGdtZW50GAMgASgF",
          "EhQKDGhpZ2hKdWRnbWVudBgEIAEoBRITCgtsb3dKdWRnbWVudBgFIAEoBRIV",
          "Cg1sb3dlckp1ZGdtZW50GAYgASgFEhYKDmxvd2VzdEp1ZGdtZW50GAcgASgF",
          "EhsKBmlucHV0cxgIIAMoCzILLklucHV0RXZlbnQSJQoLbXVsdGlwbGllcnMY",
          "CSADKAsyEC5NdWx0aXBsaWVyRXZlbnQSGwoGcGFpbnRzGAogAygLMgsuUGFp",
          "bnRFdmVudBIQCghsb29wVW5pdBgLIAEoBRIrCg5qdWRnbWVudE1ldGVycxgM",
          "IAMoCzITLkp1ZGdtZW50TWV0ZXJFdmVudBIvChBhdWRpb011bHRpcGxpZXJz",
          "GA0gAygLMhUuQXVkaW9NdWx0aXBsaWVyRXZlbnQSGQoRbGV2eWluZ011bHRp",
          "cGxpZXIYDiABKAESHgoWbGV2eWluZ0F1ZGlvTXVsdGlwbGllchgPIAEoASJJ",
          "CgpJbnB1dEV2ZW50Eg0KBWlucHV0GAEgASgFEgwKBHdhaXQYAiABKAESDgoG",
          "bm90ZUlEGAMgASgFEg4KBmp1ZGdlZBgEIAEoBSJICg9NdWx0aXBsaWVyRXZl",
          "bnQSEgoKbXVsdGlwbGllchgBIAEoARIMCgR3YWl0GAIgASgBEhMKC2lzQXV0",
          "b0V2ZW50GAMgASgIIkkKEkp1ZGdtZW50TWV0ZXJFdmVudBIVCg1qdWRnbWVu",
          "dE1ldGVyGAEgASgBEgwKBHdhaXQYAiABKAESDgoGYXNzaXN0GAMgASgFIlkK",
          "ClBhaW50RXZlbnQSEQoJaGl0UG9pbnRzGAEgASgBEg0KBXN0YW5kGAIgASgF",
          "EgwKBGJhbmQYAyABKAUSDQoFcG9pbnQYBCABKAESDAoEd2FpdBgFIAEoASI9",
          "ChRBdWRpb011bHRpcGxpZXJFdmVudBIXCg9hdWRpb011bHRpcGxpZXIYASAB",
          "KAESDAoEd2FpdBgCIAEoAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Comment), global::Comment.Parser, new[]{ "Date", "HighestJudgment", "HigherJudgment", "HighJudgment", "LowJudgment", "LowerJudgment", "LowestJudgment", "Inputs", "Multipliers", "Paints", "LoopUnit", "JudgmentMeters", "AudioMultipliers", "LevyingMultiplier", "LevyingAudioMultiplier" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::InputEvent), global::InputEvent.Parser, new[]{ "Input", "Wait", "NoteID", "Judged" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MultiplierEvent), global::MultiplierEvent.Parser, new[]{ "Multiplier", "Wait", "IsAutoEvent" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JudgmentMeterEvent), global::JudgmentMeterEvent.Parser, new[]{ "JudgmentMeter", "Wait", "Assist" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PaintEvent), global::PaintEvent.Parser, new[]{ "HitPoints", "Stand", "Band", "Point", "Wait" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AudioMultiplierEvent), global::AudioMultiplierEvent.Parser, new[]{ "AudioMultiplier", "Wait" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Comment : pb::IMessage<Comment>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Comment> _parser = new pb::MessageParser<Comment>(() => new Comment());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Comment> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Comment() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Comment(Comment other) : this() {
    date_ = other.date_;
    highestJudgment_ = other.highestJudgment_;
    higherJudgment_ = other.higherJudgment_;
    highJudgment_ = other.highJudgment_;
    lowJudgment_ = other.lowJudgment_;
    lowerJudgment_ = other.lowerJudgment_;
    lowestJudgment_ = other.lowestJudgment_;
    inputs_ = other.inputs_.Clone();
    multipliers_ = other.multipliers_.Clone();
    paints_ = other.paints_.Clone();
    loopUnit_ = other.loopUnit_;
    judgmentMeters_ = other.judgmentMeters_.Clone();
    audioMultipliers_ = other.audioMultipliers_.Clone();
    levyingMultiplier_ = other.levyingMultiplier_;
    levyingAudioMultiplier_ = other.levyingAudioMultiplier_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Comment Clone() {
    return new Comment(this);
  }

  /// <summary>Field number for the "date" field.</summary>
  public const int DateFieldNumber = 1;
  private string date_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Date {
    get { return date_; }
    set {
      date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "highestJudgment" field.</summary>
  public const int HighestJudgmentFieldNumber = 2;
  private int highestJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int HighestJudgment {
    get { return highestJudgment_; }
    set {
      highestJudgment_ = value;
    }
  }

  /// <summary>Field number for the "higherJudgment" field.</summary>
  public const int HigherJudgmentFieldNumber = 3;
  private int higherJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int HigherJudgment {
    get { return higherJudgment_; }
    set {
      higherJudgment_ = value;
    }
  }

  /// <summary>Field number for the "highJudgment" field.</summary>
  public const int HighJudgmentFieldNumber = 4;
  private int highJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int HighJudgment {
    get { return highJudgment_; }
    set {
      highJudgment_ = value;
    }
  }

  /// <summary>Field number for the "lowJudgment" field.</summary>
  public const int LowJudgmentFieldNumber = 5;
  private int lowJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LowJudgment {
    get { return lowJudgment_; }
    set {
      lowJudgment_ = value;
    }
  }

  /// <summary>Field number for the "lowerJudgment" field.</summary>
  public const int LowerJudgmentFieldNumber = 6;
  private int lowerJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LowerJudgment {
    get { return lowerJudgment_; }
    set {
      lowerJudgment_ = value;
    }
  }

  /// <summary>Field number for the "lowestJudgment" field.</summary>
  public const int LowestJudgmentFieldNumber = 7;
  private int lowestJudgment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LowestJudgment {
    get { return lowestJudgment_; }
    set {
      lowestJudgment_ = value;
    }
  }

  /// <summary>Field number for the "inputs" field.</summary>
  public const int InputsFieldNumber = 8;
  private static readonly pb::FieldCodec<global::InputEvent> _repeated_inputs_codec
      = pb::FieldCodec.ForMessage(66, global::InputEvent.Parser);
  private readonly pbc::RepeatedField<global::InputEvent> inputs_ = new pbc::RepeatedField<global::InputEvent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::InputEvent> Inputs {
    get { return inputs_; }
  }

  /// <summary>Field number for the "multipliers" field.</summary>
  public const int MultipliersFieldNumber = 9;
  private static readonly pb::FieldCodec<global::MultiplierEvent> _repeated_multipliers_codec
      = pb::FieldCodec.ForMessage(74, global::MultiplierEvent.Parser);
  private readonly pbc::RepeatedField<global::MultiplierEvent> multipliers_ = new pbc::RepeatedField<global::MultiplierEvent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::MultiplierEvent> Multipliers {
    get { return multipliers_; }
  }

  /// <summary>Field number for the "paints" field.</summary>
  public const int PaintsFieldNumber = 10;
  private static readonly pb::FieldCodec<global::PaintEvent> _repeated_paints_codec
      = pb::FieldCodec.ForMessage(82, global::PaintEvent.Parser);
  private readonly pbc::RepeatedField<global::PaintEvent> paints_ = new pbc::RepeatedField<global::PaintEvent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PaintEvent> Paints {
    get { return paints_; }
  }

  /// <summary>Field number for the "loopUnit" field.</summary>
  public const int LoopUnitFieldNumber = 11;
  private int loopUnit_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LoopUnit {
    get { return loopUnit_; }
    set {
      loopUnit_ = value;
    }
  }

  /// <summary>Field number for the "judgmentMeters" field.</summary>
  public const int JudgmentMetersFieldNumber = 12;
  private static readonly pb::FieldCodec<global::JudgmentMeterEvent> _repeated_judgmentMeters_codec
      = pb::FieldCodec.ForMessage(98, global::JudgmentMeterEvent.Parser);
  private readonly pbc::RepeatedField<global::JudgmentMeterEvent> judgmentMeters_ = new pbc::RepeatedField<global::JudgmentMeterEvent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::JudgmentMeterEvent> JudgmentMeters {
    get { return judgmentMeters_; }
  }

  /// <summary>Field number for the "audioMultipliers" field.</summary>
  public const int AudioMultipliersFieldNumber = 13;
  private static readonly pb::FieldCodec<global::AudioMultiplierEvent> _repeated_audioMultipliers_codec
      = pb::FieldCodec.ForMessage(106, global::AudioMultiplierEvent.Parser);
  private readonly pbc::RepeatedField<global::AudioMultiplierEvent> audioMultipliers_ = new pbc::RepeatedField<global::AudioMultiplierEvent>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::AudioMultiplierEvent> AudioMultipliers {
    get { return audioMultipliers_; }
  }

  /// <summary>Field number for the "levyingMultiplier" field.</summary>
  public const int LevyingMultiplierFieldNumber = 14;
  private double levyingMultiplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LevyingMultiplier {
    get { return levyingMultiplier_; }
    set {
      levyingMultiplier_ = value;
    }
  }

  /// <summary>Field number for the "levyingAudioMultiplier" field.</summary>
  public const int LevyingAudioMultiplierFieldNumber = 15;
  private double levyingAudioMultiplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double LevyingAudioMultiplier {
    get { return levyingAudioMultiplier_; }
    set {
      levyingAudioMultiplier_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Comment);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Comment other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Date != other.Date) return false;
    if (HighestJudgment != other.HighestJudgment) return false;
    if (HigherJudgment != other.HigherJudgment) return false;
    if (HighJudgment != other.HighJudgment) return false;
    if (LowJudgment != other.LowJudgment) return false;
    if (LowerJudgment != other.LowerJudgment) return false;
    if (LowestJudgment != other.LowestJudgment) return false;
    if(!inputs_.Equals(other.inputs_)) return false;
    if(!multipliers_.Equals(other.multipliers_)) return false;
    if(!paints_.Equals(other.paints_)) return false;
    if (LoopUnit != other.LoopUnit) return false;
    if(!judgmentMeters_.Equals(other.judgmentMeters_)) return false;
    if(!audioMultipliers_.Equals(other.audioMultipliers_)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LevyingMultiplier, other.LevyingMultiplier)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LevyingAudioMultiplier, other.LevyingAudioMultiplier)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Date.Length != 0) hash ^= Date.GetHashCode();
    if (HighestJudgment != 0) hash ^= HighestJudgment.GetHashCode();
    if (HigherJudgment != 0) hash ^= HigherJudgment.GetHashCode();
    if (HighJudgment != 0) hash ^= HighJudgment.GetHashCode();
    if (LowJudgment != 0) hash ^= LowJudgment.GetHashCode();
    if (LowerJudgment != 0) hash ^= LowerJudgment.GetHashCode();
    if (LowestJudgment != 0) hash ^= LowestJudgment.GetHashCode();
    hash ^= inputs_.GetHashCode();
    hash ^= multipliers_.GetHashCode();
    hash ^= paints_.GetHashCode();
    if (LoopUnit != 0) hash ^= LoopUnit.GetHashCode();
    hash ^= judgmentMeters_.GetHashCode();
    hash ^= audioMultipliers_.GetHashCode();
    if (LevyingMultiplier != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LevyingMultiplier);
    if (LevyingAudioMultiplier != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LevyingAudioMultiplier);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Date.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Date);
    }
    if (HighestJudgment != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(HighestJudgment);
    }
    if (HigherJudgment != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(HigherJudgment);
    }
    if (HighJudgment != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(HighJudgment);
    }
    if (LowJudgment != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LowJudgment);
    }
    if (LowerJudgment != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(LowerJudgment);
    }
    if (LowestJudgment != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LowestJudgment);
    }
    inputs_.WriteTo(output, _repeated_inputs_codec);
    multipliers_.WriteTo(output, _repeated_multipliers_codec);
    paints_.WriteTo(output, _repeated_paints_codec);
    if (LoopUnit != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(LoopUnit);
    }
    judgmentMeters_.WriteTo(output, _repeated_judgmentMeters_codec);
    audioMultipliers_.WriteTo(output, _repeated_audioMultipliers_codec);
    if (LevyingMultiplier != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(LevyingMultiplier);
    }
    if (LevyingAudioMultiplier != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(LevyingAudioMultiplier);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Date.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Date);
    }
    if (HighestJudgment != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(HighestJudgment);
    }
    if (HigherJudgment != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(HigherJudgment);
    }
    if (HighJudgment != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(HighJudgment);
    }
    if (LowJudgment != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(LowJudgment);
    }
    if (LowerJudgment != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(LowerJudgment);
    }
    if (LowestJudgment != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(LowestJudgment);
    }
    inputs_.WriteTo(ref output, _repeated_inputs_codec);
    multipliers_.WriteTo(ref output, _repeated_multipliers_codec);
    paints_.WriteTo(ref output, _repeated_paints_codec);
    if (LoopUnit != 0) {
      output.WriteRawTag(88);
      output.WriteInt32(LoopUnit);
    }
    judgmentMeters_.WriteTo(ref output, _repeated_judgmentMeters_codec);
    audioMultipliers_.WriteTo(ref output, _repeated_audioMultipliers_codec);
    if (LevyingMultiplier != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(LevyingMultiplier);
    }
    if (LevyingAudioMultiplier != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(LevyingAudioMultiplier);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Date.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
    }
    if (HighestJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HighestJudgment);
    }
    if (HigherJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HigherJudgment);
    }
    if (HighJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(HighJudgment);
    }
    if (LowJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LowJudgment);
    }
    if (LowerJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LowerJudgment);
    }
    if (LowestJudgment != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LowestJudgment);
    }
    size += inputs_.CalculateSize(_repeated_inputs_codec);
    size += multipliers_.CalculateSize(_repeated_multipliers_codec);
    size += paints_.CalculateSize(_repeated_paints_codec);
    if (LoopUnit != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoopUnit);
    }
    size += judgmentMeters_.CalculateSize(_repeated_judgmentMeters_codec);
    size += audioMultipliers_.CalculateSize(_repeated_audioMultipliers_codec);
    if (LevyingMultiplier != 0D) {
      size += 1 + 8;
    }
    if (LevyingAudioMultiplier != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Comment other) {
    if (other == null) {
      return;
    }
    if (other.Date.Length != 0) {
      Date = other.Date;
    }
    if (other.HighestJudgment != 0) {
      HighestJudgment = other.HighestJudgment;
    }
    if (other.HigherJudgment != 0) {
      HigherJudgment = other.HigherJudgment;
    }
    if (other.HighJudgment != 0) {
      HighJudgment = other.HighJudgment;
    }
    if (other.LowJudgment != 0) {
      LowJudgment = other.LowJudgment;
    }
    if (other.LowerJudgment != 0) {
      LowerJudgment = other.LowerJudgment;
    }
    if (other.LowestJudgment != 0) {
      LowestJudgment = other.LowestJudgment;
    }
    inputs_.Add(other.inputs_);
    multipliers_.Add(other.multipliers_);
    paints_.Add(other.paints_);
    if (other.LoopUnit != 0) {
      LoopUnit = other.LoopUnit;
    }
    judgmentMeters_.Add(other.judgmentMeters_);
    audioMultipliers_.Add(other.audioMultipliers_);
    if (other.LevyingMultiplier != 0D) {
      LevyingMultiplier = other.LevyingMultiplier;
    }
    if (other.LevyingAudioMultiplier != 0D) {
      LevyingAudioMultiplier = other.LevyingAudioMultiplier;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Date = input.ReadString();
          break;
        }
        case 16: {
          HighestJudgment = input.ReadInt32();
          break;
        }
        case 24: {
          HigherJudgment = input.ReadInt32();
          break;
        }
        case 32: {
          HighJudgment = input.ReadInt32();
          break;
        }
        case 40: {
          LowJudgment = input.ReadInt32();
          break;
        }
        case 48: {
          LowerJudgment = input.ReadInt32();
          break;
        }
        case 56: {
          LowestJudgment = input.ReadInt32();
          break;
        }
        case 66: {
          inputs_.AddEntriesFrom(input, _repeated_inputs_codec);
          break;
        }
        case 74: {
          multipliers_.AddEntriesFrom(input, _repeated_multipliers_codec);
          break;
        }
        case 82: {
          paints_.AddEntriesFrom(input, _repeated_paints_codec);
          break;
        }
        case 88: {
          LoopUnit = input.ReadInt32();
          break;
        }
        case 98: {
          judgmentMeters_.AddEntriesFrom(input, _repeated_judgmentMeters_codec);
          break;
        }
        case 106: {
          audioMultipliers_.AddEntriesFrom(input, _repeated_audioMultipliers_codec);
          break;
        }
        case 113: {
          LevyingMultiplier = input.ReadDouble();
          break;
        }
        case 121: {
          LevyingAudioMultiplier = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Date = input.ReadString();
          break;
        }
        case 16: {
          HighestJudgment = input.ReadInt32();
          break;
        }
        case 24: {
          HigherJudgment = input.ReadInt32();
          break;
        }
        case 32: {
          HighJudgment = input.ReadInt32();
          break;
        }
        case 40: {
          LowJudgment = input.ReadInt32();
          break;
        }
        case 48: {
          LowerJudgment = input.ReadInt32();
          break;
        }
        case 56: {
          LowestJudgment = input.ReadInt32();
          break;
        }
        case 66: {
          inputs_.AddEntriesFrom(ref input, _repeated_inputs_codec);
          break;
        }
        case 74: {
          multipliers_.AddEntriesFrom(ref input, _repeated_multipliers_codec);
          break;
        }
        case 82: {
          paints_.AddEntriesFrom(ref input, _repeated_paints_codec);
          break;
        }
        case 88: {
          LoopUnit = input.ReadInt32();
          break;
        }
        case 98: {
          judgmentMeters_.AddEntriesFrom(ref input, _repeated_judgmentMeters_codec);
          break;
        }
        case 106: {
          audioMultipliers_.AddEntriesFrom(ref input, _repeated_audioMultipliers_codec);
          break;
        }
        case 113: {
          LevyingMultiplier = input.ReadDouble();
          break;
        }
        case 121: {
          LevyingAudioMultiplier = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputEvent : pb::IMessage<InputEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputEvent> _parser = new pb::MessageParser<InputEvent>(() => new InputEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputEvent(InputEvent other) : this() {
    input_ = other.input_;
    wait_ = other.wait_;
    noteID_ = other.noteID_;
    judged_ = other.judged_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputEvent Clone() {
    return new InputEvent(this);
  }

  /// <summary>Field number for the "input" field.</summary>
  public const int InputFieldNumber = 1;
  private int input_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Input {
    get { return input_; }
    set {
      input_ = value;
    }
  }

  /// <summary>Field number for the "wait" field.</summary>
  public const int WaitFieldNumber = 2;
  private double wait_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Wait {
    get { return wait_; }
    set {
      wait_ = value;
    }
  }

  /// <summary>Field number for the "noteID" field.</summary>
  public const int NoteIDFieldNumber = 3;
  private int noteID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoteID {
    get { return noteID_; }
    set {
      noteID_ = value;
    }
  }

  /// <summary>Field number for the "judged" field.</summary>
  public const int JudgedFieldNumber = 4;
  private int judged_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Judged {
    get { return judged_; }
    set {
      judged_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Input != other.Input) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Wait, other.Wait)) return false;
    if (NoteID != other.NoteID) return false;
    if (Judged != other.Judged) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Input != 0) hash ^= Input.GetHashCode();
    if (Wait != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Wait);
    if (NoteID != 0) hash ^= NoteID.GetHashCode();
    if (Judged != 0) hash ^= Judged.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Input != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Input);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (NoteID != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NoteID);
    }
    if (Judged != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Judged);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Input != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Input);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (NoteID != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NoteID);
    }
    if (Judged != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Judged);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Input != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Input);
    }
    if (Wait != 0D) {
      size += 1 + 8;
    }
    if (NoteID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoteID);
    }
    if (Judged != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Judged);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputEvent other) {
    if (other == null) {
      return;
    }
    if (other.Input != 0) {
      Input = other.Input;
    }
    if (other.Wait != 0D) {
      Wait = other.Wait;
    }
    if (other.NoteID != 0) {
      NoteID = other.NoteID;
    }
    if (other.Judged != 0) {
      Judged = other.Judged;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Input = input.ReadInt32();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          NoteID = input.ReadInt32();
          break;
        }
        case 32: {
          Judged = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Input = input.ReadInt32();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          NoteID = input.ReadInt32();
          break;
        }
        case 32: {
          Judged = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MultiplierEvent : pb::IMessage<MultiplierEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MultiplierEvent> _parser = new pb::MessageParser<MultiplierEvent>(() => new MultiplierEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MultiplierEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MultiplierEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MultiplierEvent(MultiplierEvent other) : this() {
    multiplier_ = other.multiplier_;
    wait_ = other.wait_;
    isAutoEvent_ = other.isAutoEvent_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MultiplierEvent Clone() {
    return new MultiplierEvent(this);
  }

  /// <summary>Field number for the "multiplier" field.</summary>
  public const int MultiplierFieldNumber = 1;
  private double multiplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Multiplier {
    get { return multiplier_; }
    set {
      multiplier_ = value;
    }
  }

  /// <summary>Field number for the "wait" field.</summary>
  public const int WaitFieldNumber = 2;
  private double wait_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Wait {
    get { return wait_; }
    set {
      wait_ = value;
    }
  }

  /// <summary>Field number for the "isAutoEvent" field.</summary>
  public const int IsAutoEventFieldNumber = 3;
  private bool isAutoEvent_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsAutoEvent {
    get { return isAutoEvent_; }
    set {
      isAutoEvent_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MultiplierEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MultiplierEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Multiplier, other.Multiplier)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Wait, other.Wait)) return false;
    if (IsAutoEvent != other.IsAutoEvent) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Multiplier != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Multiplier);
    if (Wait != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Wait);
    if (IsAutoEvent != false) hash ^= IsAutoEvent.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Multiplier != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Multiplier);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (IsAutoEvent != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsAutoEvent);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Multiplier != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Multiplier);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (IsAutoEvent != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsAutoEvent);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Multiplier != 0D) {
      size += 1 + 8;
    }
    if (Wait != 0D) {
      size += 1 + 8;
    }
    if (IsAutoEvent != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MultiplierEvent other) {
    if (other == null) {
      return;
    }
    if (other.Multiplier != 0D) {
      Multiplier = other.Multiplier;
    }
    if (other.Wait != 0D) {
      Wait = other.Wait;
    }
    if (other.IsAutoEvent != false) {
      IsAutoEvent = other.IsAutoEvent;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Multiplier = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          IsAutoEvent = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Multiplier = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          IsAutoEvent = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class JudgmentMeterEvent : pb::IMessage<JudgmentMeterEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JudgmentMeterEvent> _parser = new pb::MessageParser<JudgmentMeterEvent>(() => new JudgmentMeterEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JudgmentMeterEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JudgmentMeterEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JudgmentMeterEvent(JudgmentMeterEvent other) : this() {
    judgmentMeter_ = other.judgmentMeter_;
    wait_ = other.wait_;
    assist_ = other.assist_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JudgmentMeterEvent Clone() {
    return new JudgmentMeterEvent(this);
  }

  /// <summary>Field number for the "judgmentMeter" field.</summary>
  public const int JudgmentMeterFieldNumber = 1;
  private double judgmentMeter_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double JudgmentMeter {
    get { return judgmentMeter_; }
    set {
      judgmentMeter_ = value;
    }
  }

  /// <summary>Field number for the "wait" field.</summary>
  public const int WaitFieldNumber = 2;
  private double wait_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Wait {
    get { return wait_; }
    set {
      wait_ = value;
    }
  }

  /// <summary>Field number for the "assist" field.</summary>
  public const int AssistFieldNumber = 3;
  private int assist_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Assist {
    get { return assist_; }
    set {
      assist_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JudgmentMeterEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JudgmentMeterEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(JudgmentMeter, other.JudgmentMeter)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Wait, other.Wait)) return false;
    if (Assist != other.Assist) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (JudgmentMeter != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(JudgmentMeter);
    if (Wait != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Wait);
    if (Assist != 0) hash ^= Assist.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (JudgmentMeter != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(JudgmentMeter);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (Assist != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Assist);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (JudgmentMeter != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(JudgmentMeter);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (Assist != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Assist);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (JudgmentMeter != 0D) {
      size += 1 + 8;
    }
    if (Wait != 0D) {
      size += 1 + 8;
    }
    if (Assist != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Assist);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JudgmentMeterEvent other) {
    if (other == null) {
      return;
    }
    if (other.JudgmentMeter != 0D) {
      JudgmentMeter = other.JudgmentMeter;
    }
    if (other.Wait != 0D) {
      Wait = other.Wait;
    }
    if (other.Assist != 0) {
      Assist = other.Assist;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          JudgmentMeter = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          Assist = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          JudgmentMeter = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
        case 24: {
          Assist = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PaintEvent : pb::IMessage<PaintEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PaintEvent> _parser = new pb::MessageParser<PaintEvent>(() => new PaintEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PaintEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PaintEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PaintEvent(PaintEvent other) : this() {
    hitPoints_ = other.hitPoints_;
    stand_ = other.stand_;
    band_ = other.band_;
    point_ = other.point_;
    wait_ = other.wait_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PaintEvent Clone() {
    return new PaintEvent(this);
  }

  /// <summary>Field number for the "hitPoints" field.</summary>
  public const int HitPointsFieldNumber = 1;
  private double hitPoints_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double HitPoints {
    get { return hitPoints_; }
    set {
      hitPoints_ = value;
    }
  }

  /// <summary>Field number for the "stand" field.</summary>
  public const int StandFieldNumber = 2;
  private int stand_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Stand {
    get { return stand_; }
    set {
      stand_ = value;
    }
  }

  /// <summary>Field number for the "band" field.</summary>
  public const int BandFieldNumber = 3;
  private int band_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Band {
    get { return band_; }
    set {
      band_ = value;
    }
  }

  /// <summary>Field number for the "point" field.</summary>
  public const int PointFieldNumber = 4;
  private double point_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Point {
    get { return point_; }
    set {
      point_ = value;
    }
  }

  /// <summary>Field number for the "wait" field.</summary>
  public const int WaitFieldNumber = 5;
  private double wait_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Wait {
    get { return wait_; }
    set {
      wait_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PaintEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PaintEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(HitPoints, other.HitPoints)) return false;
    if (Stand != other.Stand) return false;
    if (Band != other.Band) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Point, other.Point)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Wait, other.Wait)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HitPoints != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(HitPoints);
    if (Stand != 0) hash ^= Stand.GetHashCode();
    if (Band != 0) hash ^= Band.GetHashCode();
    if (Point != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Point);
    if (Wait != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Wait);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HitPoints != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(HitPoints);
    }
    if (Stand != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Stand);
    }
    if (Band != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Band);
    }
    if (Point != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Point);
    }
    if (Wait != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Wait);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HitPoints != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(HitPoints);
    }
    if (Stand != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Stand);
    }
    if (Band != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Band);
    }
    if (Point != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Point);
    }
    if (Wait != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Wait);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HitPoints != 0D) {
      size += 1 + 8;
    }
    if (Stand != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stand);
    }
    if (Band != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Band);
    }
    if (Point != 0D) {
      size += 1 + 8;
    }
    if (Wait != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PaintEvent other) {
    if (other == null) {
      return;
    }
    if (other.HitPoints != 0D) {
      HitPoints = other.HitPoints;
    }
    if (other.Stand != 0) {
      Stand = other.Stand;
    }
    if (other.Band != 0) {
      Band = other.Band;
    }
    if (other.Point != 0D) {
      Point = other.Point;
    }
    if (other.Wait != 0D) {
      Wait = other.Wait;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          HitPoints = input.ReadDouble();
          break;
        }
        case 16: {
          Stand = input.ReadInt32();
          break;
        }
        case 24: {
          Band = input.ReadInt32();
          break;
        }
        case 33: {
          Point = input.ReadDouble();
          break;
        }
        case 41: {
          Wait = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          HitPoints = input.ReadDouble();
          break;
        }
        case 16: {
          Stand = input.ReadInt32();
          break;
        }
        case 24: {
          Band = input.ReadInt32();
          break;
        }
        case 33: {
          Point = input.ReadDouble();
          break;
        }
        case 41: {
          Wait = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AudioMultiplierEvent : pb::IMessage<AudioMultiplierEvent>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AudioMultiplierEvent> _parser = new pb::MessageParser<AudioMultiplierEvent>(() => new AudioMultiplierEvent());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AudioMultiplierEvent> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommentReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioMultiplierEvent() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioMultiplierEvent(AudioMultiplierEvent other) : this() {
    audioMultiplier_ = other.audioMultiplier_;
    wait_ = other.wait_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioMultiplierEvent Clone() {
    return new AudioMultiplierEvent(this);
  }

  /// <summary>Field number for the "audioMultiplier" field.</summary>
  public const int AudioMultiplierFieldNumber = 1;
  private double audioMultiplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double AudioMultiplier {
    get { return audioMultiplier_; }
    set {
      audioMultiplier_ = value;
    }
  }

  /// <summary>Field number for the "wait" field.</summary>
  public const int WaitFieldNumber = 2;
  private double wait_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Wait {
    get { return wait_; }
    set {
      wait_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AudioMultiplierEvent);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AudioMultiplierEvent other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AudioMultiplier, other.AudioMultiplier)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Wait, other.Wait)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AudioMultiplier != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AudioMultiplier);
    if (Wait != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Wait);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AudioMultiplier != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(AudioMultiplier);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AudioMultiplier != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(AudioMultiplier);
    }
    if (Wait != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Wait);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AudioMultiplier != 0D) {
      size += 1 + 8;
    }
    if (Wait != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AudioMultiplierEvent other) {
    if (other == null) {
      return;
    }
    if (other.AudioMultiplier != 0D) {
      AudioMultiplier = other.AudioMultiplier;
    }
    if (other.Wait != 0D) {
      Wait = other.Wait;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          AudioMultiplier = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          AudioMultiplier = input.ReadDouble();
          break;
        }
        case 17: {
          Wait = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
